class_name NetworkProtocol
extends RefCounted

const VERSION: int = 2

const CHANNEL_CONTROL: int = 0
const CHANNEL_MOVEMENT: int = 1
const CHANNEL_WORLD: int = 2

enum MessageType {
	HELLO = 0,
	HELLO_ACCEPTED = 1,
	REJECT = 2,
	WORLD_SNAPSHOT = 3,
	REQUEST_WORLD_SNAPSHOT = 4,
	CLIENT_WORLD_READY = 5,
	PLAYER_SPAWN = 6,
	PLAYER_DESPAWN = 7,
	PLAYER_INPUT = 8,
	PLAYER_STATE = 9,
	REQUEST_DAMAGE_WALL = 10,
	WORLD_TILES_CHANGED = 11,
	REQUEST_WORLD_JOIN_DATA = 12,
	WORLD_JOIN_DATA = 13,
	CLIENT_WORLD_LOADED = 14,
	WORLD_CATCH_UP = 15,
	WORLD_SYNC_COMPLETE = 16,
}


enum RejectReason {
	NONE = -1,
	HOST_NOT_ACCEPTING_NEW_CLIENTS = 0,
	SESSION_FULL = 1,
}
